obj-$(CONFIG_CHARGER_SMB347_Z370CG)	+= battery_smb347.o
obj-$(CONFIG_GAUGE_SN700002_Z370CG)	+= sn700002_battery_core.o
obj-$(CONFIG_COVER_CHARGER_SMB358_Z370CG)	+= cover_battery_smb358.o
obj-$(CONFIG_COVER_GAUGE_UG31XX_Z370CG)	+= cover_upi_ug31xx/
